language: go
go:
- "1.8"
- master
script:
- set +e &&
  sudo apt-get install -y git libnetfilter-queue-dev libpcap-dev protobuf-compiler python3-pip python3 python3-pyqt5
- echo "Running go get protoc-gen-go" &&
  go get github.com/golang/protobuf/protoc-gen-go
- echo "Running go get dep" &&
  go get -u github.com/golang/dep/cmd/dep &&
  cd "$GOPATH/src/github.com/golang/dep" &&
  echo "intalling/upgrading pip" &&
  pip install --upgrade --user pip &&
  echo "installing/upgrading pip3" &&
  python3 -m pip install --user --upgrade pip &&
  echo "installing dep" &&
  ./install.sh 
- export "PATH=$PATH:$GOPATH/bin" &&
  echo "Instaling grpcio-tools" &&
  python3 -m pip install --user grpcio-tools &&
  echo "installed grpcio-tools" &&
  cd "$GOPATH/src/github.com/Thermicorp/opensnitch" &&
  echo "running make deps for opensnitch" &&
  make deps
jobs:
  include:
    - stage: "sonarcloud"
      dist: trusty
      script:
        - sudo apt-get install -y git python3-pip
        - make clean
        # Wraps the compilation with the Build Wrapper to generate configuration (used
        # later by the SonarQube Scanner) into the "bw-output" folder
        - build-wrapper-linux-x86-64 --out-dir bw-output make daemon
        # Execute some tests
        #- make test
        # And finally run the SonarQube analysis - read the "sonar-project.properties"
        # file to see the specific configuration
        - sonar-scanner
    - stage: "build"
      dist: bionic
      script: |
        set +e
        sudo apt-get install -y git libnetfilter-queue-dev libpcap-dev protobuf-compiler python3-pip python3 python3-pyqt5
        echo "Running go get protoc-gen-go"
        go get github.com/golang/protobuf/protoc-gen-go
        echo "Running go get dep"
        go get -u github.com/golang/dep/cmd/dep
        cd "$GOPATH/src/github.com/golang/dep"
        echo "intalling/upgrading pip"
        pip install --upgrade --user pip
        echo "installing/upgrading pip3"
        python3 -m pip install --user --upgrade pip
        echo "installing dep"
        ./install.sh
        export "PATH=$PATH:$GOPATH/bin"
        echo "Instaling grpcio-tools"
        python3 -m pip install --user grpcio-tools
        echo "installed grpcio-tools"
        cd "$GOPATH/src/github.com/Thermicorp/opensnitch"
        echo "running make deps for opensnitch"
        make deps
        echo "running make -C daemon"
        make -C daemon
        echo "Making sure opensnitchd exists"
        ls -l daemon/opensnitchd

addons:
 sonarcloud:
   organization: "thermicorp"
   token:
     secure: mBD3AY6Sp+w35tRnnVrZmRv6OTg2NCBwZDXFHpd1jTKdkH7jX9VogFXT8ckN5C+h3lget1QkYM8uThwQXqo8BzvPSeSNeWKP66usl829GpMD4Rzeykv5oQBhzFyohhYJlpYaXESQkSFGPcyrdOUaDe4ve40PMG19eWvXWc5ESqkzAy9pdzOFlvAScI1CszdRo963InpyMZNPao7FP4bZyZ+v6tI7oPVS0syCd+PgQyFDtyr91+8VP1TC9icas+LjznbVmVM4hpxu9wUiZovq5tebNyNRNWY9GM8W48Op9SQr3wXr0Jtx7AKx05y9FssPI1mu/0taP5BVr5YMbHAuk1Ky4QrcKcA/aXRDscR3PJE228B0xkKAfaCMYLBueKBZNamU1E+mNhyOKnjKoR3p06F3n6GUU5bWuoT/S1CSdW/+nHDBqRjcCA3Gf8/+icGG2pvAmXE71ROxboT4CW6nv6T2gAzp9Yn4ZdjkeB9HE4gRT060vzk5tRNkFMjNFuJeQSwDBeSpHJgoE4s9j9GUoRWmMmxx779FYRhUFUS62vohDrqJasublcsXpPbMABX/bCdZHK0V0FdWv64/znKMF3JmZTD7pA3HRoIQ6M/cU8vl5OwbyPBP4Tpso1mAlrQ1Vmd2LvUT4jFSSUG2NqUoxF5dIeyHoUVWk8X0b2Gbyhg=

